export enum SPELL_NAMES {
    HOLY_VISION = "holyVision",
    HEAL = "heal",
    EXORCISM = "exorcism",
    FLAME_SHIELD = "flameShield",
    FIREBALL = "fireball",
    SLOW = "slow",
    INVISIBILITY = "invisibility",
    POLYMORPH = "polymorph",
    BLIZZARD = "blizzard",
    EYE_OF_KILROGG = "eyeOfKilrogg",
    BLOODLUST = "bloodlust",
    RAISE_DEAD = "raiseDead",
    DEATH_COIL = "deathCoil",
    WHIRLWIND = "whirlwind",
    HASTE = "haste",
    UNHOLY_ARMOR = "unholyArmor",
    RUNES = "runes",
    DEATH_AND_DECAY = "deathAndDecay",
}
