export enum UPGRADE_NAMES {
    ARROWS_1 = "arrows1",
    ARROWS_2 = "arrows2",
    SWORDS_1 = "swords1",
    SWORDS_2 = "swords2",
    SHIELDS_1 = "shields1",
    SHIELDS_2 = "shields2",
    BOAT_ATTACK_1 = "boatAttack1",
    BOAT_ATTACK_2 = "boatAttack2",
    BOAT_ARMOR_1 = "boatArmor1",
    BOAT_ARMOR_2 = "boatArmor2",
    BOAT_SPEED_1 = "boatSpeed1",
    BOAT_SPEED_2 = "boatSpeed2",
    CATAPULT_DAMAGE_1 = "catapultDamage1",
    CATAPULT_DAMAGE_2 = "catapultDamage2",
    RANGER = "ranger",
    LONGBOW = "longbow",
    SCOUTS = "scouts",
    MARKS = "marks",
}
